### ISSUE TITLE
repair select field and burnout issues

### ISSUE THREAD

**Issue by anuj672** [anuj672/calorieApp_server#11]

**Comment by anuj672** [comment]
This does not look like an error FOR SELECT

https://github.com/anuj672/calorieApp_server/blob/main/forms.py#L81

it is misleading and the README setup is missing instructions

There are 4 dbs for unknown reasons, and the one it automatically works on is test DB

So when you run the application next time
try running 
python3 insert_food_data.py (this injects data into the db from the CSV file found here [
](https://github.com/anuj672/calorieApp_server/blob/main/food_data/calories.csv)

python3 application.py

**Comment by anuj672** [comment]
@bhaveshittadwar 
@VaibhaviSangawar 
@itsJash 

what was the burnout issue?

**Comment by itsJash** [comment]
@anuj672 

There is a validation issue when inputting letters instead of numbers in the enter calories box.

**Comment by anuj672** [comment]
Thanks @itsJash  I am pushing a change which checks if the input is a number, However we need to message on GUI that only number are valid

**Comment by anuj672** [comment]
change pushed to developement, sorry took 4 commits! need coffee! hahaha will be careful, now the page does not error and does not accept alphabets, but needs some frontend work to display something

**Comment by bhaveshittadwar** [comment]
We still need to show an error when the user enters anything other than an integer.

**Comment by anuj672** [comment]
Added 2 validations, which displays messages that it should be a number. I have added it twice -> can be done better. We however are not working for decimals yet! (it does not accept decimals)

closing this task and adding a enhancement task for that!
