### ISSUE TITLE
change email in 2FA

### ISSUE THREAD

**Issue by anuj672** [anuj672/calorieApp_server#22]

**Comment by anuj672** [comment]
currently 2FA uses anujchetwani to send the email plus has a wrong subject

**Comment by VaibhaviSangawar** [comment]
what email should it use? do we set up a new email for this?

**Comment by anuj672** [comment]
@VaibhaviSangawar  yes, something that we did for project 2, with my dollar bot

**Comment by VaibhaviSangawar** [comment]
Done
