### ISSUE TITLE
user able to log in even if 2fa code not verified

### ISSUE THREAD

**Issue by VaibhaviSangawar** [anuj672/calorieApp_server#28]
There is a bug in 2FA implementation. Currently the app asks for verification code but let's the user access the entire website without filling the code.

**Comment by anuj672** [comment]
lgtm

**Comment by anuj672** [comment]
I am not able to login for a new session

**Comment by anuj672** [comment]
for some users this works and for other I got error! please check for chit4 and lmk if it is something on my system?

**Comment by VaibhaviSangawar** [comment]
its working on local systems and the users created on their systems as expected.
