### ISSUE TITLE
Make the UI responsive

### ISSUE THREAD

**Issue by bhaveshittadwar** [anuj672/calorieApp_server#3]

**Comment by bhaveshittadwar** [comment]
Did the first phase for this. Worked on the main content on the page

Before:



https://github.com/anuj672/calorieApp_server/assets/40348499/5fa0c304-18df-4c7f-9119-cb591dfe63a5



After:

https://github.com/anuj672/calorieApp_server/assets/40348499/739d2e3a-6350-4393-a52c-feac0128fdcc


Will work on header and other sections one by one in their dedicated issues.

@itsJash @itsJash @VaibhaviSangawar

**Comment by anuj672** [comment]
Rocket! looks faster now
